config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("white2_project.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("white2/",include("white2_project.white2.urls", namespace="white2")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

white2_project/users/urls.py
from django.urls import path

from white2_project.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

white2_project/white2/urls.py
from django.urls import path

from .views import ParticipantListView, ParticipantDetailView ,ParticipantUpdateView,ParticipantContactUpdateView

app_name = "white2"
urlpatterns = [
    path('', view=ParticipantListView.as_view(), name="participants"),
    path('<slug:slug>/update/', view=ParticipantUpdateView.as_view(), name="participant-update"),
    path('<slug:slug>/contact/', view=ParticipantContactUpdateView.as_view(), name="participant-contact-update"),
    path('<slug:slug>/', view=ParticipantDetailView.as_view(), name="participant"),
    
] 

white2_project/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for White2 project.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

white2_project/users/forms.py
from allauth.account.forms import SignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    
    """

white2_project/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

white2_project/white2/views.py
from audioop import add
from multiprocessing import context
from django.forms import inlineformset_factory
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.views.generic import ListView, DetailView, UpdateView,FormView
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render,redirect
from django.db import transaction
from django.forms.models import modelformset_factory
from django.template import RequestContext

from django.urls import reverse
import re

from .models import  Participant, ParticipantPhone, ParticipantEmail, ParticipantAddress
from .forms import ParticipantAddressForm, ParticipantEmailForm, ParticipantPhoneForm, ParticipantForm, PhoneFormset,EmailFormset,AddressFormset#, ParticipantStatusForm,ParticipantNonStatusForm

class ParticipantListView(ListView):
    '''
    render list of participants
    '''
    model = Participant

#    def head(self, *args, **kwargs):
#        '''
#        override head() to show midified timestamp in the HEAD
#        '''
#        last_participant = self.get_queryset().latest('datetime_updated')
#        response = HttpResponse(
#            # RFC 1123 date format.
#            headers={'Last-Modified': last_participant.datetime_updated.strftime('%a, %d %b %Y %H:%M:%S GMT')},
#        )
#        return response

    
class ParticipantDetailView(LoginRequiredMixin, DetailView):

    model = Participant
    
    def get_context_data(self, **kwargs):
        '''
        Return: participant context plus all the participant's contact details
        '''
        context = super().get_context_data(**kwargs)
        try:
            context["phone"] = ParticipantPhone.objects.filter(participant_id=context['participant'].id)
        except AttributeError:
            context["phone"] = None
        try:
            context["email"] = ParticipantEmail.objects.filter(participant_id=context['participant'].id)
        except AttributeError:
            context["email"] = None
        try:
            context["address"] = ParticipantAddress.objects.filter(participant_id=context['participant'].id)
        except AttributeError: 
            context["address"] = None
        return context

class PhoneUpdateView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'white2\participant_phone_form.html'
    model = ParticipantPhone
    form_class = ParticipantPhoneForm
    fields = ['number','type','location','primary']
    slug_field = "participant_id"
    slug_url_kwarg = "participant_id"
    lookup_url_kwarg = 'participant_id'
    success_url = 'white2:participants'
    
    def get_context_data(self, **kwargs):
        #error on next line:
        #error: Argument "formset" to "inlineformset_factory" has incompatible type "Type[ParticipantPhoneForm]"; expected "Type[BaseInlineFormSet]"
        #TODO deal with it
        PhoneFormSet = inlineformset_factory(
            Participant,
            ParticipantPhone,
            fields=('number','type','location','primary'),
            formset=ParticipantPhoneForm,
            fk_name='participant'
            )
        context = super(PhoneUpdateView,self).get_context_data(**kwargs)
        context['phone_form'] = PhoneFormSet(instance=context['Participant'])
        
        return context
    
class ParticipantUpdateView(LoginRequiredMixin,UpdateView):
    template_name = 'white2/participant_form.html'
    form_class = ParticipantForm
    model = Participant 
    
    def get_success_url(self):
        #return self.request.participant.get_absolute_url()
        return reverse('white2:participant',kwargs={'slug':self.kwargs['slug']})

class ParticipantContactUpdateView(LoginRequiredMixin,UpdateView):
    template_name = 'white2/participant_contact_form.html' 
    #form_class = ParticipantHeaderForm
    model = Participant
    #don't naad to update any fields, but they won't be available as form fields - or should I restrict this???
    fields="__all__"
        
    def get_context_data(self, **kwargs):
        context = super(ParticipantContactUpdateView,self).get_context_data(**kwargs)
        if self.request.POST:
            context['phone_formset']=PhoneFormset(self.request.POST,instance=self.object,prefix="phone")
            context['phone_formset'].full_clean()
            context['email_formset']=EmailFormset(self.request.POST,instance=self.object,prefix="email")
            context['email_formset'].full_clean()
            context['address_formset']=AddressFormset(self.request.POST,instance=self.object,prefix="address")
            context['address_formset'].full_clean()
        else:
            context['phone_formset']=PhoneFormset(instance=self.object)
            context['email_formset']=EmailFormset(instance=self.object)
            context['address_formset']=AddressFormset(instance=self.object)
        return context
    
    def post(self,request,*args,**kwargs):
        self.object = self.get_object()
        form = self.get_form()
        phone_formset = PhoneFormset(self.request.POST,prefix="phone")
        email_formset = EmailFormset(self.request.POST,prefix="email")
        address_formset = AddressFormset(self.request.POST,prefix="address")
        #phone_formset=context['phone_formset']
        #email_formset=context['email_formset']
        #address_formset=context['address_formset']
        if form.is_valid() and phone_formset.is_valid() and email_formset.is_valid() and address_formset.is_valid():
            return self.form_valid(form,phone_formset,email_formset,address_formset)
        else:
            return self.form_invalid(form,phone_formset,email_formset,address_formset)
    
    def form_valid(self,form,phone_formset,email_formset,address_formset):
        self.object=form.save()
        phone_formset.instance = self.object
        phone_formset.save()
        email_formset.instance = self.object
        email_formset.save()
        address_formset.instance = self.object
        address_formset.save()
        return HttpResponseRedirect(self.get_success_url())
        
    def form_invalid(self,form,phone_formset,email_formset,address_formset):
        return self.render_to_response(self.get_context_data(form=form,phone_formset=phone_formset,email_formset=email_formset,address_formset=address_formset))        
            
    def get_success_url(self):
        #return self.request.participant.get_absolute_url()
        return reverse('white2:participant',kwargs={'slug':self.kwargs['slug']})


        
        

white2_project/templates/white2/base.html
{% extends "base.html" %}
{% block title %}{% block head_title %}{% endblock head_title %}{% endblock title %}

{% block content %}
<div class="row">
  
    {% block inner %}{% endblock %}
  
</div>

{% endblock %}

white2_project/templates/white2/participant_contact_form.html
{% extends "white2/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_title %}Participant: {{ object.study_no }}{{ object.check_letter }}{% endblock %}

{% block inner %}
<div class="container">
  <div class="row">
    <div class="col-sm-12">

      {{form.management_form}}
      {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}

      {{phone_formset.management_form}}
      {% for hidden in phone_formset.hidden_fields %}{{ hidden }}{% endfor %}

      {{email_formset.management_form}}
      {% for hidden in email_formset.hidden_fields %}{{ hidden }}{% endfor %}

      {{address_formset.management_form}}
      {% for hidden in address_formset.hidden_fields %}{{ hidden }}{% endfor %}

      <h2>{{object.study_no}}{{object.check_letter}}: {{object.title}} {{object.initials}} {{object.surname}}</h2>

      <h4>Phone number(s)</h2>
      {%for phone in phone_formset %}
        {%for hidden in phone.hidden_fields%}{{hidden}}{%endfor%}
        {%crispy phone phone.helper %}
      {%endfor%}
      
      <h4>Email address(es)</h2>
      {%for email in email_formset%}
        {%for hidden in email.hidden_fields%}{{hidden}}{%endfor%}
        {%crispy email email.helper%}
      {%endfor%}
      
      <h4>Postal address(es)</h2>
      {%for address in address_formset%}
        {%for hidden in address.hidden_fields%}{{hidden}}{%endfor%} 
        {%crispy address address.helper%}
      {%endfor%}
        
    </div>
    
  </div>
  
</div>
{% endblock  %}

white2_project/templates/white2/participant_detail.html
{% extends "white2/base.html" %}
{% load static %}

{% block head_title %}Participant: {{ participant.study_no }}{{ participant.check_letter }}{% endblock %}

{% block inner %}
<div class="container">
  
  <div class="card-group">
  <div class="card border-primary mb-3" style="max-width: 18rem;">
    <div class="card-header">Participant details</div>
    <div class="card-body">
      <h5 class="card-title">{{ participant.study_no }} {{ participant.check_letter }}</h5>
      <p class="card-text">{% for f in participant.get_non_status_fields %}
        {% if f.name != "study_no" and f.name != "check_letter" %}
          <dt>
            <dd>{{f.label}}: <span style="font-weight:bold">{{f.value}}</span></dd>
          </dt>
        {% endif %}
      {% endfor %}</p>
    </div>
    <div class="card-footer">
      <form action="" method="post">{% csrf_token %}<a class="btn btn-primary" href="{% url 'white2:participant-update' participant.slug %}" role="button">Update details/status</a></form>
    </div>
  </div>
  
  <div class="card border-primary mb-3" style="max-width: 18rem;">
    <div class="card-header">Status</div>
    <div class="card-body">
      {%comment%}<h5 class="card-title">{{ participant.study_no }} {{ participant.check_letter }}</h5>{%endcomment%}
      <p class="card-text">{% for f in participant.get_status_fields %}
        <dt>
          {%if f.value == False%}
            <dd>{{f.label}}: <span style="font-weight:bold">No</span></dd>
          {%elif f.value == True%}
            <dd class="text-primary">{{f.label}}: <span style="font-weight:bold">Yes</span></dd>
          {%else%}<!--just in case there are any non boolean status fields in future-->
            <dd>{{f.label}}: <span style="font-weight:bold">{{f.value}}</span></dd>
          {%endif%}
        </dt>
      {% endfor %}</p>
    </div>
    <div class="card-footer">
      <form action="" method="post">{% csrf_token %}<a class="btn btn-primary" href="{% url 'white2:participant-update' participant.slug %}" role="button">Update details/status</a></form>
    </div>
  </div>
  
  <div class="card border-primary mb-3" style="max-width: 18rem;">
    <div class="card-header">Contact details</div>
    <div class="card-body">
      {%comment%}<h5 class="card-title">{{ participant.study_no }} {{ participant.check_letter }}</h5>{%endcomment%}
      <p class="card-text">
        <h3>phone</h3>
        {% if phone == None %}No numbers saved 
        {%else%}
          {% for f in phone %}
            <dt>
              {%if f.primary == True%}
                <dd class="text-primary">{{ f.type }} <span style="font-weight:bold">{{ f.number }}</span> (main)</dd>
              {%else%}
                <dd>{{ f.type }} <span style="font-weight:bold">{{ f.number }}</span></dd>
              {%endif%}
            </dt>
          {%endfor%}
          {%comment%}<button class="btn btn-primary" href="{% url 'white2:phone-update' participant.study_no %}" role="button">Update phone</button>{%endcomment%}
        {%endif%}
        <h3>email</h3>
        {% if email == None %}No email saved 
        {%else%}
          {% for f in email %}
            <dt>
              <dd>
                {%if f.primary == True%}
                  <p class="text-primary"><span style="font-weight:bold">{{ f.email }}</span>{{ f.description }} (main)</p>
                {%else%}
                  <span style="font-weight:bold">{{ f.email }}</span> {{ f.description }}
                {%endif%}
              </dd>
            </dt>
          {%endfor%}
        {%endif%}
        <h3>postal address</h3>
        {% if address == None %}No postal address saved 
        {%else%}
        {% for f in address %}
          <dt>
            <dd>address needs formatting differently</dd>
          </dt>
        {%endfor%}
        {%endif%}
      </p>
    </div>
    <div class="card-footer">
      <a class="btn btn-primary" href="{% url 'white2:participant-contact-update' participant.slug %}" role="button">Update contact details</a>
    </div>
  </div>
      
    
  
</div>
{% endblock  %}

white2_project/templates/white2/participant_form.html
{% extends "white2/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_title %}Participant: {{ object.study_no }}{{ object.check_letter }}{% endblock %}

{% block inner %}
<div class="container">
  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.study_no }} {{ object.check_letter }}</h2>
      {%crispy form form.helper%}
        
    </div>
  </div>
</div>
{% endblock  %}

white2_project/templates/white2/participant_list.html
{% extends "white2/base.html" %}
{% load static %}

{% csrf_token %}

{% block inner %}
<div class="container">

  <h1>Participant List</h1>
  {% if participant_list %}
  <ul>
    {% for participant in participant_list %}
      <li>
        <a href="{{ participant.get_absolute_url }}">
          {{ participant.study_no }}{{ participant.check_letter }} {{ participant.surname }} ({{participant.first_name}})
        </a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no participants in the library.</p>
  {% endif %}


</div>


{% endblock inner %}

white2_project/templates/white2/participant_phone_form.html
{% extends "white2/base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block head_title %}Participant: {{ object.study_no }}{{ object.check_letter }}{% endblock %}

{% block inner %}
<div class="container">
  
  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.study_no }} {{ object.check_letter }}</h2>
        
          {%crispy phone %}
    
    </div>
  </div>
  

</div>
{% endblock  %}